### ISSUE TITLE
Adjusting image length is not working

### ISSUE THREAD

**Issue by mathisgauthey** [TuanManhCao/digital-garden#10]
Hi there, I love your project, it is probably the simpliest yet most beautiful obsidian publish alternative.

But I can't get around the following problem : I can't adjust image size.

Using `![[paypal_logo.png|25x25]]` is not working.
But `![[paypal_logo.png]]` is fine, with the image inside `public/images` of course.

Any idea how to fix this ? Thanks in advance !

**Comment by TuanManhCao** [comment]
Hey @mathisgauthey !

Thanks for the compliment. That makes my day! I haven't give much thought about that yet, but I think it can be done through having some sort of CSS and HTML transformation their. 

Or you'll just have to have a smaller image resolution to work around that.

**Comment by mathisgauthey** [comment]
I managed to use PowerToys and bulk resize my images. I don't know anything about CSS and HTML yet, so I won't be able to help for now but might in the future !
