### ISSUE TITLE
Clone or Fork?

### ISSUE THREAD

**Issue by fncll** [TuanManhCao/digital-garden#3]
I'd like to use digital-garden via netlify. I've cloned this repository as instructed. But what do I need to do to make the repository visible to Netlify? Do I push my local repository to something of my own on github somehow? I'm really not familiar with git, so I am probably missing something really basic.

**Comment by ssbarnea** [comment]
While reading about the idea I was quite interested but when I later discovered that the tool has not testing pipeline and you basically fork the build tool in your repo to use it, I had a WTF moment.

I will watch what happens but until the code/tool would not be decoupled from the template, I see no reason to invest time in it, as I do not fancy doing any syncs.

For the moment I will keep using hugo for my blog, while keeping an eye on how things develop.
